### ISSUE TITLE
Indkøb af bolsjer

### ISSUE THREAD

**Issue by Athas** [Athas/ucph.dk#11]
Fagrådet har tildelt 150kr fra Prosapuljen så vi kan købe en pose bolsjer til at belønne pull requests.  Hvad skal vi købe, og hvornår?

**Comment by Eckankar** [comment]
Jeg vil foreslå [Sømods Bolcher](http://soemods-bolcher.dk/)! Det ligger lige ved Nørreport, og de laver rigtig gode bolcher.

For 135 kr kan man få [500g blandede bolcher i pose](http://soemods-bolcher.dk/da/blandede-i-pose/20-blandede-bolcher-250g.html), og for 165 kr (lidt over budgettet) kan man få [500g blandede bolcher i dåse](http://soemods-bolcher.dk/da/blandinger-i-glas-og-daser/26-dase-med-500g-blandede.html).

Hvis man lyster kan man endda se dem lave bolcherne i butikken! (Hvis man går ind i den i baggården; de har to butikker lige ved siden af hinanden, vist nok.)

[Åbningstiderne kan findes her](http://soemods-candies.dk/aabningstider/).

**Comment by Athas** [comment]
Jeg kan godt lide at de starter med at brokke sig over Nørregade Bolcher.

Hvornår skal vi så tage derned?

**Comment by Athas** [comment]
Dette problem er blevet løst.
