### ISSUE TITLE
Stephen Alstrup er ikke længere vice head

### ISSUE THREAD

**Issue by dybber** [Athas/ucph.dk#20]
On 9 February 2015 at 09:27, Jørgen P. Bansler <bansler@di.ku.dk> wrote:
> Stephen and I have agreed that Stephen as of today will step down as vice
> head of department for innovation and business collaboration. 
>
> Stephen has served as vice head since 2012 and made a number of important
> contributions to the department. Among other things, he has successfully
> contributed to increasing DIKU student recruitment, increased the
> department's focus on EU/industrial-research projects, and participated in
> external communication and networking activities.
>
> Stephen and I have, nevertheless, agreed that he should be relieved of these
> managerial and administrative duties in order for him to dedicate more time
> to his research.
>  
> Stephen will continue to contribute to the department’s strategic
> initiatives with respect to external collaboration.
>
> Best regards,
> Jørgen
>
>
> --
> Jørgen P. Bansler, PhD, Professor
> Head of Department
>
> Department of Computer Science
> University of Copenhagen
> Njalsgade 128-132, Building 24, 5.
> DK-2300 Copenhagen S
> Denmark
> Tel +45 2381 1332
> www.diku.dk 
>

**Comment by Athas** [comment]
Lav et pull request og scor et bolsje!
