### ISSUE TITLE
I cannot see the dancing dinosaur in links or lynx

### ISSUE THREAD

**Issue by svip** [Athas/ucph.dk#30]
Having used my main browser links, I noticed that the dinosaur was not dancing, even though I've read about it in numerous commit messages and issues.

**Comment by nqpz** [comment]
Have you tried using ELinks?

**Comment by svip** [comment]
Unfortunately, there is no dancing in elinks either.

**Comment by nqpz** [comment]
I would like to close this bug with a closing remark from René Descartes:

> Thus, all Philosophy is like a tree, of which Metaphysics is the root, Physics the trunk, and all the other sciences the branches that grow out of this trunk, which are reduced to three principals, namely, Medicine, Mechanics, and Ethics. By the science of Morals, I understand the highest and most perfect which, presupposing an entire knowledge of the other sciences, is the last degree of wisdom.

Synes du stadig at det er vigtigt af se en dansende dinosaur?  Du kan ikke svare, for denne issue er lukket.

**Comment by nqpz** [comment]
Vent, man kan godt svare på lukkede issues?

**Comment by svip** [comment]
Hedder det ikke sag på dansk?

**Comment by nqpz** [comment]
Det sag hun også i går.
