### ISSUE TITLE
The radio's keybindings are in the way of my browsing

### ISSUE THREAD

**Issue by nqpz** [Athas/ucph.dk#31]
I depend on keybindings in my browser to navigate, and the radio steals them from me, making it dificult for me to navigate away from the page, and accidentally playing P1 instead.

I have found out that if I set `keyEnabled` to `false` in the player setup, my keybindings aren't captured.  However, this would annoy the rest of the world, so I would like a way to set a cookie or something like that.

**Comment by Athas** [comment]
No cookies!  Make the Right Decision and stick to it.  Pointlessly
over-configurable software is a pox.

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
On 2015-03-27 16:46:30, Troels Henriksen wrote:
> No cookies!  Make the Right Decision and stick to it.  Pointlessly
> over-configurable software is a pox.

But there is no Right Thing in this case!  Or if there is, it's the
wrong thing for me!

**Comment by Athas** [comment]
"Niels G. W. Serup" <notifications@github.com> writes:

> On 2015-03-27 16:46:30, Troels Henriksen wrote:
>> No cookies!  Make the Right Decision and stick to it.  Pointlessly
>> over-configurable software is a pox.
>
> But there is no Right Thing in this case!  Or if there is, it's the
> wrong thing for me!

Which keys are captured by the player?

I personally suggest just disabling all keyboard controls.

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
On 2015-03-27 17:13:52, Troels Henriksen wrote:
> "Niels G. W. Serup" <notifications@github.com> writes:
> 
> > On 2015-03-27 16:46:30, Troels Henriksen wrote:
> >> No cookies!  Make the Right Decision and stick to it.  Pointlessly
> >> over-configurable software is a pox.
> >
> > But there is no Right Thing in this case!  Or if there is, it's the
> > wrong thing for me!
> 
> Which keys are captured by the player?
> 
> I personally suggest just disabling all keyboard controls.

What does @MikkelStorgaard have to say?

**Comment by dybber** [comment]
Jeg gætter på at flertallet af de besøgene ikke er der pga. radioen. Så
dræb dens irriterende genvejstaster.
No cookies! Make the Right Decision and stick to it. Pointlessly
over-configurable software is a pox.

-- 
\ Troels
/\ Henriksen

—
Reply to this email directly or view it on GitHub
<https://github.com/Athas/ucph.dk/issues/31#issuecomment-87124595>.

**Comment by nqpz** [comment]
Hov, jeg satte faktisk `keyEnabled` til `false` ved mit megacommit her tidligere.  Nu stjæler siden ikke ens taster!  Jeg lukker sagen som løst, og så må nogen åbne den igen hvis de er *meget* uenige.
