### ISSUE TITLE
The tabs breaks the back button

### ISSUE THREAD

**Issue by kfl** [Athas/ucph.dk#4]
The tabs seems to break my back button (FF 36.0 Beta 7).

**Comment by Athas** [comment]
Why do you want to leave?

**Comment by kfl** [comment]
I don't want to leave.

I was just using the IRC tab, then using the Ordbog tab, then trying to go BACK to the IRC tab. It didn't work, I got confused and ended up on Amazon where I somehow bought a sewing machine :crying_cat_face:

**Comment by kfl** [comment]
Indeed ef614c88a8b0c495572c56dc4b82aea3c2ec8793 solves the problem.

Now just need to figure out how to operate the sewing machine.

**Comment by MikkelStorgaard** [comment]
Dear kfl.

I have pushed more Javascript to the tree. This usually helps.
