### ISSUE TITLE
The tabs do not work in the Dillo browser

### ISSUE THREAD

**Issue by nqpz** [Athas/ucph.dk#5]
Using Dillo 3.0.4, I cannot use the tabs on [http://ucph.dk/](http://ucph.dk/)!

I want to chat with my friends on IRC, but it just doesn't work!

And why is there a dinousaur that's not dancing???

**Comment by MikkelStorgaard** [comment]
Dillo does not support Javascript yet, which can generate problems in your case.
According to the Dillo team[0], Javascript is on a "low priority" to be implemented in the browser.
This is equivalent to "Sure I can do a hand stand, I just don't feel like it right now."

Have you tried throwing more money at the problem?

Maybe you can borrow a computer at the library, and visit ucph.dk from there?

[0] http://www.dillo.org/Plans.html

**Comment by nqpz** [comment]
Fixed in 18ca8ce860720aebb4a64bd363b540406a39a03e.

**Comment by nqpz** [comment]
That is, JavaScript is still used, but now the tabs are accessed the old-school way with <a name="#tabs1-forside"> and so on if in non-js mode.
