### ISSUE TITLE
Ordbog is lacking

### ISSUE THREAD

**Issue by MikkelStorgaard** [Athas/ucph.dk#6]
I have forgotten every single word I know in Danish, and I am only allowed to learn from http://ucph.dk/#tabs1-ordbog .

I have a date tonight, and it'll probably go bad if I don't know at least twenty words by then.
"Trutværk trutværk trutværk" does not make for a great conversation.

plz.
Best regards, Mikkel Storgaard Knudsen

**Comment by Orkeren** [comment]
Extended the dictionary to 79 expressions and will thus mark this as solved

**Comment by svip** [comment]
Hvordan gik din date?

**Comment by MikkelStorgaard** [comment]
Den blev rykket til på torsdag.

**Comment by Athas** [comment]
Hvordan gik det så?  Fik du udnyttet dit forstørrede ordforråd?
