### ISSUE TITLE
Hvordan gik Mikkels date?

### ISSUE THREAD

**Issue by svip** [Athas/ucph.dk#8]
I sag #6 skrev Mikkel at skulle på en date, men kun kunne ord fra ordbogen.  Desværre nåede ingen at opdatere ordbogen inden Mikkel skulle på date selvsamme aften.

Så jeg vil vide hvordan hans date gik.

**Comment by MikkelStorgaard** [comment]
Jeg har aflyst daten, fordi jeg kom frem til, at jeg i længden nok ikke ville fungere med en 26-årig fyr, som bruger "xD" i ca. hver tredje sætning.
